# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: GitMirrorLib

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

#Your build pipeline references a secret variable named ‘pat’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository to https://github.com/sampanu/gitmirrored.git'
  inputs:
    sourceGitRepositoryPersonalAccessToken: '$(pat)'

    destinationGitRepositoryUri: 'https://github.com/sampanu/gitmirrored.git'

    destinationGitRepositoryPersonalAccessToken: '$(gitpat)'
