#!/bin/sh
#!C:/Program\ Files/Git/usr/bin/sh.exe
# (pre-commit)
# Fail if any matching words are present in the diff

powershell -noprofile -executionpolicy unrestricted -file .git/hooks/PreCommit.ps1